services:
  sonar_db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_SONAR_DATABASE}
    volumes:
      - sonar_db:/bitnami/postgresql
    networks:
      - sonar

  sonarqube:
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/${POSTGRESQL_SONAR_DATABASE}
      SONAR_JDBC_USERNAME: ${POSTGRESQL_USERNAME}
      SONAR_JDBC_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonar
    depends_on:
      - sonar_db

networks:
  sonar:
    driver: bridge

volumes:
  sonar_db:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
