services:
  api_db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=gigauth
    volumes:
      - api_db:/bitnami/postgresql
    networks:
      - app

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - app
    depends_on:
      - api_db

networks:
  app:
    driver: bridge

volumes:
  api_db:
